# Basic set up for two package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "/IvyBot/IvyBot"
    schedule:
      interval: "daily"
